platform :ios, '12.0'

target 'ResumeBuilder' do
  use_frameworks!

  pod 'Toast-Swift'
  pod 'Gallery'
  pod 'CropViewController'
  pod 'IQKeyboardManager'
  pod 'RealmSwift', '~>10'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

  target 'ResumeBuilderTests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'RxBlocking', '6.5.0'
    pod 'RxTest', '6.5.0'
  end

  target 'ResumeBuilderUITests' do
    # Pods for testing
  end

end
