platform :ios, '12.0'

target 'ResumeBuilder' do
  use_frameworks!

  pod 'SkeletonView'
  pod 'RealmSwift', '~>10'

  target 'ResumeBuilderTests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end

  target 'ResumeBuilderUITests' do
    # Pods for testing
  end

end
